// Code generated by protoc-gen-go. DO NOT EDIT.
// source: korpc.proto

package korpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Options struct {
	ServiceAccount       string      `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	ContainerConcurrency int32       `protobuf:"varint,2,opt,name=container_concurrency,json=containerConcurrency,proto3" json:"container_concurrency,omitempty"`
	Resources            *Resource   `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Env                  []*KeyValue `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	TimeoutSeconds       int64       `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ae5685d888d925, []int{0}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

func (m *Options) GetContainerConcurrency() int32 {
	if m != nil {
		return m.ContainerConcurrency
	}
	return 0
}

func (m *Options) GetResources() *Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Options) GetEnv() []*KeyValue {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Options) GetTimeoutSeconds() int64 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type KeyValue struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ae5685d888d925, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Resource struct {
	Limits               map[string]string `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Requests             map[string]string `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ae5685d888d925, []int{2}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetLimits() map[string]string {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *Resource) GetRequests() map[string]string {
	if m != nil {
		return m.Requests
	}
	return nil
}

type Resource_Block struct {
	Cpu                  string   `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               string   `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource_Block) Reset()         { *m = Resource_Block{} }
func (m *Resource_Block) String() string { return proto.CompactTextString(m) }
func (*Resource_Block) ProtoMessage()    {}
func (*Resource_Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ae5685d888d925, []int{2, 0}
}

func (m *Resource_Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource_Block.Unmarshal(m, b)
}
func (m *Resource_Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource_Block.Marshal(b, m, deterministic)
}
func (m *Resource_Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource_Block.Merge(m, src)
}
func (m *Resource_Block) XXX_Size() int {
	return xxx_messageInfo_Resource_Block.Size(m)
}
func (m *Resource_Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Resource_Block proto.InternalMessageInfo

func (m *Resource_Block) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *Resource_Block) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

var E_Options = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Options)(nil),
	Field:         98374687,
	Name:          "korpc.options",
	Tag:           "bytes,98374687,opt,name=options",
	Filename:      "korpc.proto",
}

func init() {
	proto.RegisterType((*Options)(nil), "korpc.Options")
	proto.RegisterType((*KeyValue)(nil), "korpc.KeyValue")
	proto.RegisterType((*Resource)(nil), "korpc.Resource")
	proto.RegisterMapType((map[string]string)(nil), "korpc.Resource.LimitsEntry")
	proto.RegisterMapType((map[string]string)(nil), "korpc.Resource.RequestsEntry")
	proto.RegisterType((*Resource_Block)(nil), "korpc.Resource.Block")
	proto.RegisterExtension(E_Options)
}

func init() { proto.RegisterFile("korpc.proto", fileDescriptor_d7ae5685d888d925) }

var fileDescriptor_d7ae5685d888d925 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb5, 0x71, 0x9d, 0x26, 0x13, 0x91, 0xa2, 0x55, 0x41, 0xab, 0x20, 0x90, 0xc9, 0x85,
	0x5c, 0x70, 0x05, 0xe1, 0x40, 0xcb, 0x09, 0x10, 0xa7, 0x82, 0x90, 0x16, 0x89, 0x6b, 0x94, 0x6e,
	0x86, 0x62, 0xd9, 0xde, 0x31, 0xfb, 0x11, 0xc9, 0x4f, 0xc3, 0x09, 0x89, 0xe7, 0xe2, 0x19, 0x78,
	0x00, 0xe4, 0xf5, 0xba, 0x2d, 0x15, 0x17, 0x6e, 0x3b, 0xff, 0x0f, 0xeb, 0xb7, 0xde, 0x81, 0x59,
	0x49, 0xa6, 0x51, 0x79, 0x63, 0xc8, 0x11, 0x4f, 0xc3, 0xb0, 0xc8, 0x2e, 0x89, 0x2e, 0x2b, 0x3c,
	0x09, 0xe2, 0x85, 0xff, 0x72, 0xb2, 0x43, 0xab, 0x4c, 0xd1, 0x38, 0x32, 0x7d, 0x70, 0xf9, 0x8b,
	0xc1, 0xe1, 0xc7, 0xc6, 0x15, 0xa4, 0x2d, 0x7f, 0x02, 0x47, 0x16, 0xcd, 0xbe, 0x50, 0xb8, 0xd9,
	0x2a, 0x45, 0x5e, 0x3b, 0xc1, 0x32, 0xb6, 0x9a, 0xca, 0x79, 0x94, 0x5f, 0xf7, 0x2a, 0x5f, 0xc3,
	0x3d, 0x45, 0xda, 0x6d, 0x0b, 0x8d, 0x66, 0xa3, 0x48, 0x2b, 0x6f, 0x0c, 0x6a, 0xd5, 0x8a, 0x51,
	0xc6, 0x56, 0xa9, 0x3c, 0xbe, 0x32, 0xdf, 0x5e, 0x7b, 0xfc, 0x29, 0x4c, 0x0d, 0x5a, 0xf2, 0x46,
	0xa1, 0x15, 0x49, 0xc6, 0x56, 0xb3, 0xe7, 0x47, 0x79, 0xcf, 0x2c, 0xa3, 0x2e, 0xaf, 0x13, 0xfc,
	0x31, 0x24, 0xa8, 0xf7, 0xe2, 0x20, 0x4b, 0x6e, 0x04, 0xcf, 0xb1, 0xfd, 0xbc, 0xad, 0x3c, 0xca,
	0xce, 0xeb, 0x78, 0x5d, 0x51, 0x23, 0x79, 0xb7, 0xb1, 0xa8, 0x48, 0xef, 0xac, 0x48, 0x33, 0xb6,
	0x4a, 0xe4, 0x3c, 0xca, 0x9f, 0x7a, 0x75, 0xf9, 0x02, 0x26, 0x43, 0x93, 0x73, 0x38, 0xd0, 0xdb,
	0x1a, 0xe3, 0xcd, 0xc2, 0x99, 0x1f, 0x43, 0xba, 0xef, 0xcc, 0xc0, 0x3f, 0x95, 0xfd, 0xb0, 0xfc,
	0x31, 0x82, 0xc9, 0x40, 0xc6, 0xd7, 0x30, 0xae, 0x8a, 0xba, 0x70, 0x56, 0xb0, 0x40, 0xf4, 0xe0,
	0x16, 0x7a, 0xfe, 0x3e, 0xb8, 0xef, 0xb4, 0x33, 0xad, 0x8c, 0x51, 0x7e, 0x0a, 0x13, 0x83, 0xdf,
	0x3c, 0x5a, 0x67, 0xc5, 0x28, 0xd4, 0x1e, 0xde, 0xae, 0xc9, 0xe8, 0xf7, 0xc5, 0xab, 0xf8, 0xe2,
	0x19, 0xa4, 0x6f, 0x2a, 0x52, 0x25, 0xbf, 0x0b, 0x89, 0x6a, 0x7c, 0xc4, 0xed, 0x8e, 0xfc, 0x3e,
	0x8c, 0x6b, 0xac, 0xc9, 0xb4, 0x11, 0x37, 0x4e, 0x8b, 0x53, 0x98, 0xdd, 0x80, 0xe8, 0x8a, 0x25,
	0xb6, 0x43, 0xb1, 0xc4, 0xf6, 0xdf, 0xd7, 0x3c, 0x1b, 0xbd, 0x64, 0x8b, 0x57, 0x70, 0xe7, 0x2f,
	0x90, 0xff, 0x29, 0x9f, 0x9d, 0xc3, 0x21, 0xc5, 0x0d, 0x7a, 0x94, 0xf7, 0x0b, 0x97, 0x0f, 0x0b,
	0x97, 0x7f, 0x40, 0xf7, 0x95, 0x76, 0x71, 0xc3, 0xc4, 0xf7, 0x9f, 0xbf, 0xf3, 0xf0, 0xf2, 0xf3,
	0xf8, 0x1f, 0xa2, 0x21, 0x87, 0x2f, 0x5c, 0x8c, 0x43, 0x73, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0x84, 0xa4, 0x24, 0xce, 0x02, 0x00, 0x00,
}
