// Code generated by protoc-gen-go. DO NOT EDIT.
// source: korpc.proto

package korpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Options struct {
	ServiceAccount       string      `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	ContainerConcurrency int32       `protobuf:"varint,2,opt,name=container_concurrency,json=containerConcurrency,proto3" json:"container_concurrency,omitempty"`
	Env                  []*KeyValue `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ae5685d888d925, []int{0}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

func (m *Options) GetContainerConcurrency() int32 {
	if m != nil {
		return m.ContainerConcurrency
	}
	return 0
}

func (m *Options) GetEnv() []*KeyValue {
	if m != nil {
		return m.Env
	}
	return nil
}

type KeyValue struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ae5685d888d925, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

var E_Options = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Options)(nil),
	Field:         98374687,
	Name:          "korpc.options",
	Tag:           "bytes,98374687,opt,name=options",
	Filename:      "korpc.proto",
}

func init() {
	proto.RegisterType((*Options)(nil), "korpc.Options")
	proto.RegisterType((*KeyValue)(nil), "korpc.KeyValue")
	proto.RegisterExtension(E_Options)
}

func init() { proto.RegisterFile("korpc.proto", fileDescriptor_d7ae5685d888d925) }

var fileDescriptor_d7ae5685d888d925 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0xdb, 0xb5, 0x76, 0x16, 0x5a, 0x08, 0x15, 0x16, 0x0f, 0x12, 0x7b, 0x71, 0x4f,
	0x29, 0xb4, 0x9e, 0xbc, 0x89, 0xc7, 0x22, 0x42, 0x0e, 0x5e, 0xcb, 0x76, 0x3a, 0xd6, 0xc5, 0x9a,
	0x59, 0xb2, 0xd9, 0x85, 0xbe, 0x82, 0x2f, 0xe1, 0xd5, 0x07, 0xf4, 0x01, 0xa4, 0x49, 0x56, 0x6f,
	0x99, 0xff, 0x4b, 0x32, 0xff, 0x07, 0xd9, 0x3b, 0xdb, 0x1a, 0x55, 0x6d, 0xd9, 0xb1, 0x48, 0xfd,
	0x70, 0x25, 0xf7, 0xcc, 0xfb, 0x03, 0x2d, 0x7c, 0xb8, 0x6d, 0x5f, 0x17, 0x3b, 0x6a, 0xd0, 0x56,
	0xb5, 0x63, 0x1b, 0x2e, 0xce, 0x3f, 0x13, 0x18, 0x3d, 0xd7, 0xae, 0x62, 0xd3, 0x88, 0x5b, 0x98,
	0x36, 0x64, 0xbb, 0x0a, 0x69, 0x53, 0x22, 0x72, 0x6b, 0x5c, 0x9e, 0xc8, 0xa4, 0x18, 0xeb, 0x49,
	0x8c, 0x1f, 0x42, 0x2a, 0x56, 0x70, 0x89, 0x6c, 0x5c, 0x59, 0x19, 0xb2, 0x1b, 0x64, 0x83, 0xad,
	0xb5, 0x64, 0xf0, 0x98, 0x9f, 0xc9, 0xa4, 0x48, 0xf5, 0xec, 0x0f, 0x3e, 0xfe, 0x33, 0x71, 0x03,
	0x03, 0x32, 0x5d, 0x3e, 0x94, 0x83, 0x22, 0x5b, 0x4e, 0x55, 0x68, 0xbb, 0xa6, 0xe3, 0x4b, 0x79,
	0x68, 0x49, 0x9f, 0xd8, 0xfc, 0x0e, 0x2e, 0xfa, 0x40, 0x08, 0x18, 0x9a, 0xf2, 0x83, 0x62, 0x03,
	0x7f, 0x16, 0x33, 0x48, 0xbb, 0x13, 0xf4, 0x7b, 0xc6, 0x3a, 0x0c, 0xf7, 0x6b, 0x18, 0x71, 0x34,
	0xb8, 0x56, 0x41, 0x58, 0xf5, 0xc2, 0xea, 0x89, 0xdc, 0x1b, 0xef, 0xa2, 0x61, 0xfe, 0xf5, 0xfd,
	0xa3, 0x64, 0x52, 0x64, 0xcb, 0x49, 0xdc, 0x1f, 0x81, 0xee, 0x7f, 0xd8, 0x9e, 0xfb, 0x97, 0xab,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x57, 0xbe, 0xce, 0x4e, 0x01, 0x00, 0x00,
}
